name: Simple Schedule Test

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각 실행
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduled123 run at $(date -u)"
