name: Scheduled Job

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run scheduled task
        run: npm run build

      - name: Commit changes
        run: |
          git config user.name "Park-Yu-Jin"
          git config user.email "lits111@naver.com"
          git add .
          git commit -m "chore: auto update data" || exit 0
          git push
